### ISSUE TITLE
Organization name change broke CI pipelines

### ISSUE THREAD

**Issue by Y-LyN-10** [aibex/slack-rich-notify#5]
Hello! 

We love to use that GitHub CI Action. Unfortunately, such a change as organization/owner rename can cause major CI failures such as: ​`Unable to resolve actions. Repository not found : aibexhq/slack-rich-notify.`

It looks more like a GitHub issue because according to the [documentation](https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization#changes-that-occur-automatically), references should have been automatically redirected:

```
GitHub automatically redirects references to your repositories. Web links to your organization's existing repositories will continue to work. This can take a few minutes to complete after you initiate the change.
```

I tried to rerun the pipelines a few times over the past hour, but it didn't get resolved automatically. I would like to ask if this is a permanent change? I would be happy to open PR to update your documentation.

Greetings!

**Comment by thecodedrift** [comment]
Hi @Y-LyN-10, thanks for filing the issue! We would be happy to accept a PR with this change, as we expect the organization name to continue as `aibex`.
